spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/subscription
    username: pve123
    password: test123!
    driver-class-name: org.postgresql.Driver