spring:
  application:
    name: saas-billing-api
  config:
    import:
      - "application-swagger.yml"
  profiles:
    active: ${spring.profiles.active}
    group:
      local:
        - datasource
        - flyway
        - jpa
