version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: subscription-postgres
    restart: always
    environment:
      POSTGRES_DB: subscription
      POSTGRES_USER: pve123
      POSTGRES_PASSWORD: test123!
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
